services:
  peshqadam:
    build:
      context: .
      args:
        VITE_ADMIN_IDS: ${ADMIN_IDS}
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - public

networks:
  public:
    external: true
    name: jamm-deploy_public
